#!/usr/bin/env python3
"""Generate sstv_tables.h: the fixed-point tables sstv_core.c uses, so the core needs no floating
point at run time (apps are built soft-float). Rerun after changing any constant here."""

import math

FS = 12000
MIX_HZ = 1900
FIR_TAPS, FIR_CUTOFF = 33, 900
CORDIC_ITERS = 14

# sine, 1024 entries over a full turn, Q15
sin_tab = [round(32767 * math.sin(2 * math.pi * i / 1024)) for i in range(1024)]
# Hamming-windowed sinc low-pass, Q15, normalized to unity DC gain
h = []
for k in range(FIR_TAPS):
    m = k - (FIR_TAPS - 1) / 2
    s = 2 * FIR_CUTOFF / FS * (1 if m == 0 else math.sin(2 * math.pi * FIR_CUTOFF / FS * m)
                                / (2 * math.pi * FIR_CUTOFF / FS * m))
    h.append(s * (0.54 - 0.46 * math.cos(2 * math.pi * k / (FIR_TAPS - 1))))
g = sum(h)
fir = [round(32768 * v / g) for v in h]
# CORDIC: atan(2^-i) in binary angle units (2*pi = 65536)
cordic = [round(math.atan(2.0 ** -i) / (2 * math.pi) * 65536) for i in range(CORDIC_ITERS)]

with open("sstv_tables.h", "w") as f:
    f.write("/* Generated by gen_tables.py -- do not edit. */\n#ifndef SSTV_TABLES_H\n#define SSTV_TABLES_H\n\n")
    f.write("#include <stdint.h>\n\n")
    f.write(f"#define SSTV_FS {FS}\n#define SSTV_MIX_STEP {round(MIX_HZ / FS * 2**32)}u  /* {MIX_HZ} Hz, Q32 turns/sample */\n")
    f.write(f"#define SSTV_FIR_TAPS {FIR_TAPS}\n#define SSTV_CORDIC_ITERS {CORDIC_ITERS}\n\n")
    for name, vals, typ in (("sstv_sin1024", sin_tab, "int16_t"), ("sstv_fir", fir, "int16_t"),
                            ("sstv_cordic_atan", cordic, "uint16_t")):
        f.write(f"static const {typ} {name}[{len(vals)}] = {{\n")
        for i in range(0, len(vals), 12):
            f.write("    " + ", ".join(str(v) for v in vals[i:i + 12]) + ",\n")
        f.write("};\n\n")
    f.write("#endif\n")
print("wrote sstv_tables.h")
